// Generated by scripts/split-audio.mjs — do not edit by hand.
// Edit scripts/tracklist.mjs and re-run `npm run split:audio`.

export interface Track {
  /** File name under `AUDIO_BASE`. */
  readonly file: string;
  readonly artist: string;
  readonly title: string;
  /** Runtime in seconds, measured off the split rather than the tracklist. */
  readonly seconds: number;
}

/** Where the split tracks are served from. */
export const AUDIO_BASE = "/audio/tracks";

export const TRACKS: readonly Track[] = [
  {
    file: "01-ennio-mano-pale.mp3",
    artist: "Ennio Máno",
    title: "Pale",
    seconds: 192.99,
  },
  {
    file: "02-oakwood-station-yesterdays-we-don-t-forget.mp3",
    artist: "Oakwood Station",
    title: "Yesterdays We Don't Forget",
    seconds: 208.01,
  },
  {
    file: "03-the-flax-whisky-on-the-rocks.mp3",
    artist: "The Flax",
    title: "Whisky on the Rocks",
    seconds: 199.00,
  },
  {
    file: "04-ennio-mano-les-pipos.mp3",
    artist: "Ennio Máno",
    title: "Les Pipos",
    seconds: 165.98,
  },
  {
    file: "05-hara-noda-spring-street.mp3",
    artist: "Hara Noda",
    title: "Spring Street",
    seconds: 213.00,
  },
  {
    file: "06-oakwood-station-in-the-peak-bar.mp3",
    artist: "Oakwood Station",
    title: "In the Peak Bar",
    seconds: 201.01,
  },
  {
    file: "07-hara-noda-catcher.mp3",
    artist: "Hara Noda",
    title: "Catcher",
    seconds: 231.99,
  },
  {
    file: "08-ennio-mano-bows.mp3",
    artist: "Ennio Máno",
    title: "Bows",
    seconds: 181.00,
  },
  {
    file: "09-jerry-mchoy-adrian-rambling-shoreditch.mp3",
    artist: "Jerry McHoy",
    title: "Adrian Rambling Shoreditch",
    seconds: 188.00,
  },
  {
    file: "10-magnus-ringblom-quartet-whatever-happens-next.mp3",
    artist: "Magnus Ringblom Quartet",
    title: "Whatever Happens Next",
    seconds: 232.99,
  },
  {
    file: "11-ennio-mano-light-dance.mp3",
    artist: "Ennio Máno",
    title: "Light Dance",
    seconds: 217.00,
  },
  {
    file: "12-ennio-mano-midair.mp3",
    artist: "Ennio Máno",
    title: "Midair",
    seconds: 150.02,
  },
  {
    file: "13-oakwood-station-back-when-we-met.mp3",
    artist: "Oakwood Station",
    title: "Back When We Met",
    seconds: 185.00,
  },
  {
    file: "14-ennio-mano-spring-blossoms.mp3",
    artist: "Ennio Máno",
    title: "Spring Blossoms",
    seconds: 228.99,
  },
  {
    file: "15-ennio-mano-aves.mp3",
    artist: "Ennio Máno",
    title: "Aves",
    seconds: 247.01,
  },
  {
    file: "16-oakwood-station-space-for-two.mp3",
    artist: "Oakwood Station",
    title: "Space for Two",
    seconds: 196.00,
  },
  {
    file: "17-ennio-mano-arrow.mp3",
    artist: "Ennio Máno",
    title: "Arrow",
    seconds: 210.99,
  },
  {
    file: "18-magnus-ringblom-quartet-if-i-m-not-mistaken.mp3",
    artist: "Magnus Ringblom Quartet",
    title: "If I'm Not Mistaken",
    seconds: 203.00,
  },
  {
    file: "19-hara-noda-swimmer.mp3",
    artist: "Hara Noda",
    title: "Swimmer",
    seconds: 228.00,
  },
  {
    file: "20-hara-noda-slide.mp3",
    artist: "Hara Noda",
    title: "Slide",
    seconds: 191.01,
  },
  {
    file: "21-ennio-mano-ages-ago.mp3",
    artist: "Ennio Máno",
    title: "Ages Ago",
    seconds: 199.00,
  },
  {
    file: "22-oakwood-station-kind-of-a-miracle.mp3",
    artist: "Oakwood Station",
    title: "Kind of a Miracle",
    seconds: 189.00,
  },
  {
    file: "23-franz-gordon-i-fly-with-you.mp3",
    artist: "Franz Gordon",
    title: "I Fly With You",
    seconds: 240.01,
  },
  {
    file: "24-oakwood-station-glancing-at-the-moon.mp3",
    artist: "Oakwood Station",
    title: "Glancing at the Moon",
    seconds: 221.00,
  },
  {
    file: "25-oakwood-station-parkside-lane.mp3",
    artist: "Oakwood Station",
    title: "Parkside Lane",
    seconds: 121.99,
  },
  {
    file: "26-bladverk-band-memories-from-the-past.mp3",
    artist: "Bladverk Band",
    title: "Memories from the Past",
    seconds: 235.99,
  },
  {
    file: "27-jerry-mchoy-lights-down-low.mp3",
    artist: "Jerry McHoy",
    title: "Lights Down Low",
    seconds: 208.01,
  },
  {
    file: "28-jerry-mchoy-the-messengers.mp3",
    artist: "Jerry McHoy",
    title: "The Messengers",
    seconds: 246.00,
  },
  {
    file: "29-oakwood-station-no-thoughts-of-regret.mp3",
    artist: "Oakwood Station",
    title: "No Thoughts of Regret",
    seconds: 252.00,
  },
  {
    file: "30-william-benckert-bear-cub-blues.mp3",
    artist: "William Benckert",
    title: "Bear Cub Blues",
    seconds: 212.01,
  },
  {
    file: "31-thiago-leave-your-heart-to-me.mp3",
    artist: "Thiago",
    title: "Leave Your Heart To Me",
    seconds: 243.98,
  },
  {
    file: "32-oakwood-station-treats-of-the-70-s.mp3",
    artist: "Oakwood Station",
    title: "Treats of the 70's",
    seconds: 202.00,
  },
  {
    file: "33-thiago-just-one-more-night-with-you.mp3",
    artist: "Thiago",
    title: "Just One More Night With You",
    seconds: 285.00,
  },
  {
    file: "34-oakwood-station-seeing-through-you.mp3",
    artist: "Oakwood Station",
    title: "Seeing Through You",
    seconds: 181.00,
  },
  {
    file: "35-oakwood-station-blue-spaces.mp3",
    artist: "Oakwood Station",
    title: "Blue Spaces",
    seconds: 182.10,
  },
] as const;
